In [4]:
import numpy as np

In [5]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Number of Dimensions:", arr1.ndim)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of Dimensions: 3
