In [4]:
import numpy as np

In [7]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Number of Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)
print("Size (Total Number of Elements):", arr1.size)
print("Item Size (in bytes):", arr1.itemsize)
print("Total Bytes:", arr1.nbytes)  


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of Dimensions: 3
Data Type: int64
Size (Total Number of Elements): 12
Item Size (in bytes): 8
Total Bytes: 96


In [8]:
arr2=arr1.astype(np.float64)
print("\nArray with Changed Data Type:")
print(arr2)
print("Data Type:", arr2.dtype) 


Array with Changed Data Type:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Data Type: float64
