In [19]:
#Creating numpy/n-d arrays
import numpy as np

In [20]:
arr1=np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)


In [21]:
arr2=np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [22]:
arr3=np.zeros((3, 4))
print("\n2D Array of Zeros:")
print(arr3)
print("Shape:", arr3.shape)


2D Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)


In [23]:
arr4=np.ones((2, 3))
print("\n2D Array of Ones:")
print(arr4)
print("Shape:", arr4.shape)


2D Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Shape: (2, 3)


In [24]:
aar5=np.identity(4)
print("\nIdentity Matrix:")
print(aar5)
print("Shape:", aar5.shape)


Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


In [25]:
arr6=np.random.rand(2, 3)
print("\n2D Array with Random Values:")
print(arr6)
print("Shape:", arr6.shape)


2D Array with Random Values:
[[0.12204721 0.24110426 0.67201378]
 [0.30319805 0.11161469 0.86582695]]
Shape: (2, 3)


In [26]:
arr7=np.arange(10,101,10)
print("\n1D Array with Range of Values:")
print(arr7)
print("Shape:", arr7.shape) 


1D Array with Range of Values:
[ 10  20  30  40  50  60  70  80  90 100]
Shape: (10,)


In [27]:
arr8=np.linspace(0, 1, 5)
print("\n1D Array with Linearly Spaced Values:")
print(arr8)
print("Shape:", arr8.shape) 


1D Array with Linearly Spaced Values:
[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)


In [28]:
arr9=np.copy(arr8)
print("\nCopied Array:")
print(arr9)
print("Shape:", arr9.shape) 



Copied Array:
[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
